// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// The default [FirebaseOptions] for the current platform.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_toxjgMduvIBNc72Wj6T7SHZq8nBdY44',
    appId: '1:560285959775:web:e66d28e024a61cad9dbdea',
    messagingSenderId: '560285959775',
    projectId: 'zh-music-1617505883522',
    authDomain: 'zh-music-1617505883522.firebaseapp.com',
    databaseURL: 'https://zh-music-1617505883522-default-rtdb.firebaseio.com',
    storageBucket: 'zh-music-1617505883522.appspot.com',
    measurementId: 'G-X28KZZFBS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLjnTkCrqma3x_VFe-oN6sH6sJ1rkDSzg',
    appId: '1:560285959775:android:cf1a7bcae12fc9819dbdea',
    messagingSenderId: '560285959775',
    projectId: 'zh-music-1617505883522',
    databaseURL: 'https://zh-music-1617505883522-default-rtdb.firebaseio.com',
    storageBucket: 'zh-music-1617505883522.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOyqaPCoh06g_lJbT8rQ49e9gcNvin6ow',
    appId: '1:560285959775:ios:897f6596bb8c23399dbdea',
    messagingSenderId: '560285959775',
    projectId: 'zh-music-1617505883522',
    databaseURL: 'https://zh-music-1617505883522-default-rtdb.firebaseio.com',
    storageBucket: 'zh-music-1617505883522.appspot.com',
    androidClientId: '560285959775-u7ceuhe207afvb7ofsqbtm04jks8crum.apps.googleusercontent.com',
    iosClientId: '560285959775-8lsugdma55v4tpi2hua0vl7srm8p3ce8.apps.googleusercontent.com',
    iosBundleId: 'com.example.lyric',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOyqaPCoh06g_lJbT8rQ49e9gcNvin6ow',
    appId: '1:560285959775:ios:897f6596bb8c23399dbdea',
    messagingSenderId: '560285959775',
    projectId: 'zh-music-1617505883522',
    databaseURL: 'https://zh-music-1617505883522-default-rtdb.firebaseio.com',
    storageBucket: 'zh-music-1617505883522.appspot.com',
    androidClientId: '560285959775-u7ceuhe207afvb7ofsqbtm04jks8crum.apps.googleusercontent.com',
    iosClientId: '560285959775-8lsugdma55v4tpi2hua0vl7srm8p3ce8.apps.googleusercontent.com',
    iosBundleId: 'com.example.lyric',
  );
}
